/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dti.internalballistics;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.apache.batik.dom.svg.SAXSVGDocumentFactory;
import org.apache.batik.swing.JSVGCanvas;
import org.apache.batik.util.XMLResourceDescriptor;
import org.kabeja.dxf.DXFDocument;
import org.kabeja.parser.DXFParseException;
import org.kabeja.parser.DXFParser;
import org.kabeja.parser.Parser;
import org.kabeja.parser.ParserBuilder;
import org.kabeja.svg.SVGGenerator;
import org.kabeja.xml.SAXGenerator;
import org.kabeja.xml.SAXSerializer;
import org.kabeja.xslt.SAXXMLSerializer;
import org.w3c.dom.Element;
import org.w3c.dom.svg.SVGDocument;

/**
 *
 * @author amabird
 */
public class TestSVG2 extends javax.swing.JFrame {

    /**
     * Creates new form TestSVG2
     */
    public TestSVG2() {
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        setBounds(0, 0, 449, 355);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestSVG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestSVG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestSVG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestSVG2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        InputStream is = null;
        try {
            TestSVG2 t = new TestSVG2();
            t.canvas = new JSVGCanvas();
            
            t.setLayout(null);
            t.getContentPane().add(t.canvas);
            
            
            t.setSize(400, 400);
            
            t.setVisible(true);
            
            t.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            is = t.getClass().getClassLoader().getResource("dti/image/DTIStar.dxf").openStream();
            Parser dxfParser = ParserBuilder.createDefaultParser();
            dxfParser.parse(is, DXFParser.DEFAULT_ENCODING);
            DXFDocument dXFDocument = dxfParser.getDocument();
            SAXGenerator sAXGenerator = new SVGGenerator();
            SAXSerializer sAXSerializer = new SAXXMLSerializer();
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            sAXSerializer.setOutput(byteArrayOutputStream);

            sAXGenerator.setProperties(new HashMap());

            sAXGenerator.generate(dXFDocument, sAXSerializer);
            //return byteArrayOutputStream;
            byte[] data = byteArrayOutputStream.toByteArray();
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(data);
            String svgParser = XMLResourceDescriptor.getXMLParserClassName();
            SAXSVGDocumentFactory sAXSVGDocumentFactory = new SAXSVGDocumentFactory(svgParser);
            SVGDocument sVGDocument = sAXSVGDocumentFactory.createSVGDocument(null, byteArrayInputStream);
            Element root = sVGDocument.getDocumentElement();
            System.out.println(root.getAttribute("width"));
            root.getElementsByTagName(svgParser);
            t.canvas.setSVGDocument(sVGDocument);

        } catch (IOException ex) {
            Logger.getLogger(TestSVG.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DXFParseException ex) {
            Logger.getLogger(TestSVG.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                is.close();
            } catch (IOException ex) {
                Logger.getLogger(TestSVG.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    public JSVGCanvas canvas;
    public JButton button1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
